_common: !include "../shared-package.yaml"

name: game
<<: *common

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - containers
    - base
    - reactive-banana
  <<: *library

executables:
  exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - game
    <<: *executable

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - game
    <<: *test
